clear all
close all
clc
%Read the image
I = imread('oranges.jpg');
[BW, nBW]=CM(I);
imshow(BW)
function [BW,maskedImage] = CM(RGB)
%segmentImage Segment image using auto-generated code from imageSegmenter
%  [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
%  auto-generated code from the imageSegmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 18-Jun-2020
%----------------------------------------------------


% Convert RGB image into L*a*b* color space.
X = rgb2lab(RGB);

% Create empty mask.
BW = false(size(X,1),size(X,2));

% Draw Ellipse
xPos = [643.9188 643.9188 641.1838 638.4488 638.4487 638.4488...
    641.1838 643.9188 643.9188];
yPos = [138.6197 138.6197 138.6197 138.6197 138.6197 138.6197...
    138.6197 138.6197 138.6197];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Draw Polygon
xPos = [641.1838 764.2607 890.0726 991.2692 1043.2350 1086.9957...
    1103.4060 1062.3803 947.5085 835.3718 706.8248 605.6282 531.7821...
    474.3462 452.4658 452.4658 471.6111 512.6368 572.8077];
yPos = [144.0897 105.7991 105.7991 168.7051 217.9359 321.8675 431.2692...
    554.3462 650.0726 693.8333 696.5684 663.7479 600.8419 526.9957...
    453.1496 362.8932 272.6368 209.7308 168.7051];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Draw Polygon
xPos = [1910.2436 1819.9872 1754.3462 1748.8761 1765.2863 1803.5769...
    1861.0128 1932.1239 2005.9701 2093.4915 2167.3376 2216.5684...
    2224.7735 2191.9530 2129.0470 2079.8162];
yPos = [10.0726 37.4231 165.9701 253.4915 330.0726 387.5085 431.2692...
    469.5598 483.2350 447.6795 382.0385 310.9274 206.9957 114.0043...
    31.9530 1.8675];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Draw Polygon
xPos = [1406.9957 1494.5171 1609.3889 1688.7051 1746.1410 1789.9017...
    1809.0470 1789.9017 1729.7308 1647.6795 1521.8675 1409.7308...
    1314.0043 1248.3632 1221.0128 1196.3974 1204.6026 1251.0983 1314.0043];
yPos = [491.4402 477.7650 491.4402 540.6709 598.1068 682.8932...
    770.4145 866.1410 978.2778 1041.1838 1068.5342 1060.3291 1011.0983...
    939.9872 857.9359 778.6197 688.3632 603.5769 540.6709];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Draw Polygon
xPos = [392.2949 348.5342 326.6538 323.9188 378.6197 496.2265...
    586.4829 698.6197 775.2009 865.4573 914.6880 922.8932...
    876.3974 846.3120];
yPos = [1596.3974 1519.8162 1443.2350 1322.8932 1191.6111 1106.8248...
    1063.0641 1087.6795 1123.2350 1188.8761 1295.5427...
    1432.2949 1560.8419 1596.3974];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Draw Polygon
xPos = [3.9188 129.7308 233.6624 291.0983 310.2436 258.2778 195.3718...
    126.9957 61.3547 3.9188];
yPos = [836.0556 827.8504 764.9444 655.5427 516.0556 403.9188...
    346.4829 302.7222 294.5171 308.1923];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Draw Polygon
xPos = [1092.4658 1070.5855 1065.1154 1078.7906 1138.9615 1207.3376...
    1289.3889 1409.7308 1502.7222 1587.5085 1634.0043 1661.3547...
    1658.6197 1655.8846];
yPos = [1593.6624 1522.5513 1435.0299 1347.5085 1262.7222 1216.2265...
    1172.4658 1172.4658 1210.7564 1265.4573 1342.0385 1440.5000...
    1525.2863 1590.9274];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Draw Polygon
xPos = [1940.3291 1904.7735 1904.7735 1918.4487 1934.8590...
    1975.8846 2060.6709 2159.1325 2241.1838 2336.9103 2397.0812 2397.0812];
yPos = [1596.3974 1541.6966 1478.7906 1410.4145 1344.7735 1276.3974...
    1213.4915 1164.2607 1169.7308 1186.1410 1218.9615 1599.1325];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Dilate mask with disk
radius = 1;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imdilate(BW, se);

% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

